[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sesnaimpute"
version = "0.1.0"
requires-python = "==3.9.*"
dependencies = [
    "numpy",
    "h5py",
    "scipy",
    "joblib",
    "healpy",
    "numba",
    "astropy",
    "matplotlib",
    "pandas",
    "threadpoolctl",
    "tomli",
    "beautifulsoup4",
]

[project.optional-dependencies]
download = [
    "astroquery",
    "pdfplumber",
    "pdfminer.six",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
sesnaimpute = ["data/extinction_laws/*/*", "gutcolors/tables/*.toml"]
